change respondd and alfred-announce to mesh-announce
FreifunkBremen/ansible pull request #79
Opened 2017-08-14 09:28 UTC by genofire

to solve #78

2017-08-14 09:29 UTC, genofire commented
sollte man ggf. die alten ausgecheckten repos noch löschen?
(oder ist das nicht aufgabe dieser role?)

2017-08-14 10:42 UTC, corny commented
Ja die alten Daten sollten gelöscht werden - dafür bitte eine separate Rolle erstellen.

2017-08-14 12:03 UTC, genofire commented
ups, so rebase ... nun sollte der cleanup dabei sein

2017-08-17 13:45 UTC, jplitza requested changes
Ich bin meist dafür, Aufräumarbeiten einmalig per ansible-console durchzuführen, da die Aufräum-Rollen sonst ewig im Repo versauern. Da es davon ja aber schon ein paar Rollen gibt, sträube ich mich nicht dagegen.

Hab einige andere Sachen noch angemerkt. Danke fürs generelle Angehen!

2017-08-17 13:45 UTC, jplitza commented on roles/alfred-announce-cleanup/tasks/main.yml
> +- name: Remove  alfred-announces cronjob
Doppeltes Leerzeichen

2017-08-17 13:45 UTC, jplitza commented on roles/alfred-announce-cleanup/tasks/main.yml
> +- name: Stop respondd service
Das sollte wohl ganz am Anfang passieren, bevor der Ordner gelöscht wird.

2017-08-17 13:45 UTC, jplitza commented on roles/mesh-announce/meta/main.yml
> +	- wheezy
Whitespace error

2017-08-17 13:45 UTC, jplitza commented on roles/mesh-announce/tasks/main.yml
> +- name: Install cronjob to automatically update alfred announce
Ich will Alfred loswerden, bitte also das Installieren dieses Cronjobs abhängig von einer neuen Variable (`alfred_announce` oder so) machen, da die Rollen jetzt zusammengeführt sind.

2017-08-17 18:36 UTC, genofire commented
Werde am Ende ein Squash + Merge machen (wegen den commit-Messages)

2017-10-31 10:26 UTC, jplitza approved these changes

2017-10-31 10:34 UTC, merged