[BUGFIX] change ipv6 prefix without infrastructur
FreifunkBremen/ansible pull request #81
Opened 2018-01-14 12:03 UTC by genofire

Change of `site.conf` need a change of `/lib/hosts.py`

2018-04-26 13:47 UTC, genofire commented
Findet wer den Fehler auf VPN06 ??
```
# Ansible managed

auto br-ffhb
iface br-ffhb inet static
	bridge-ports bat-ffhb
	bridge-maxwait 0
	address 10.196.0.6
	netmask 255.255.128.0
	# unreachable route in default-freifunk
	# prevents leak of data
	post-up  ip -4 route add unreachable default metric 2048 table default-freifunk
	pre-down ip -4 route del unreachable default metric 2048 table default-freifunk
	post-up  ip -6 route add unreachable default metric 2048 table default-freifunk
	pre-down ip -6 route del unreachable default metric 2048 table default-freifunk
	# rules to send stuff to VPN
	post-up  ip -4 rule add iif $IFACE table default-freifunk priority 16385
	pre-down ip -4 rule del iif $IFACE table default-freifunk priority 16385
	post-up  ip -6 rule add iif $IFACE table default-freifunk priority 16385
	pre-down ip -6 rule del iif $IFACE table default-freifunk priority 16385
	# tune ARP and IPv6 neighbor soolicitation
	post-up sysctl -p /etc/sysctl.d/main-bridge-ip-neigh-tuning.conf

iface br-ffhb inet6 static
	address fd2f:5119:f2c::6
	netmask 64
	up   ip -6 addr add fd2f:5119:f2c::6/64 dev $IFACE
	down ip -6 addr del fd2f:5119:f2c::6/64 dev $IFACE
	post-up  ip -6 route add 2001:bf7:540::/64 dev $IFACE
	pre-down ip -6 route del 2001:bf7:540::/64 dev $IFACE
```

Please review and merge this PR

2018-04-28 12:30 UTC, jplitza requested changes
Was hat vpn06 mit diesem PR zu tun? Ja, die IPv6-Config da sollte natürlich eigentlich einmal eine globale IPv6-Adresse assignen, und nicht zweimal ne ULA.

Dieser PR ist jedenfalls noch fehlerhaft.

2018-04-28 12:30 UTC, jplitza commented on roles/unbound/templates/listen-on-all-interfaces.conf
> -  interface: {{ batman_ipv6_local.address }}
Diese Änderung tut nichts.

2018-04-28 12:30 UTC, jplitza commented on roles/exit-ipv6/templates/vpn-uplink6
> +	post-down ip -6 rule del from {{ batman_ipv6_local.address }} table default-freifunk priority 16385
Hier müsste definitiv weiter "global" benutzt werden. Wir wollen ja nicht die ULAs routen, sondern das globale Präfix. Im Zweifelsfalle könnte man das `from {{...}}` auch einfach ersetzen durch `iif br-{{ site_code }}`.

2018-05-18 21:16 UTC, jplitza approved these changes

2018-05-18 21:17 UTC, jplitza commented
Ändert an der laufenden Konfiguration von vpn01 quasi nichts, scheint also korrekt zu sein.

2018-05-18 21:17 UTC, merged